/* Use this script if you need to support IE 7 and IE 6. */

window.onload = function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'icons-font\'">' + entity + '</span>' + html;
	}
	var icons = {
			'icon-checkmark' : '&#x23;',
			'icon-facebook' : '&#x25;',
			'icon-home' : '&#x21;',
			'icon-phone' : '&#x22;',
			'icon-mail' : '&#x26;',
			'icon-minus' : '&#x27;',
			'icon-plus' : '&#x28;',
			'icon-arrow-right' : '&#x29;',
			'icon-arrow-left' : '&#x2a;',
			'icon-arrow-left-2' : '&#x2b;',
			'icon-arrow-right-2' : '&#x2c;',
			'icon-arrow-down' : '&#x2d;',
			'icon-arrow-up' : '&#x2e;',
			'icon-arrow-up-2' : '&#x2f;',
			'icon-arrow-down-2' : '&#x30;',
			'icon-checkbox' : '&#x31;',
			'icon-new-tab' : '&#x32;',
			'icon-new-tab-2' : '&#x33;',
			'icon-twitter' : '&#x34;',
			'icon-twitter-2' : '&#x35;',
			'icon-facebook-2' : '&#x36;',
			'icon-google-plus' : '&#x37;',
			'icon-google-plus-2' : '&#x38;',
			'icon-gplus' : '&#x39;',
			'icon-facebook-3' : '&#x3a;',
			'icon-twitter-3' : '&#x3b;',
			'icon-feed' : '&#x3c;',
			'icon-feed-2' : '&#x3d;',
			'icon-feed-3' : '&#x3e;',
			'icon-youtube' : '&#x3f;',
			'icon-youtube-2' : '&#x40;',
			'icon-wordpress' : '&#x42;',
			'icon-tumblr' : '&#x43;',
			'icon-tumblr-2' : '&#x44;',
			'icon-android' : '&#x45;',
			'icon-finder' : '&#x46;',
			'icon-apple' : '&#x47;',
			'icon-skype' : '&#x48;',
			'icon-linkedin' : '&#x49;',
			'icon-linkedin-2' : '&#x4a;',
			'icon-file-pdf' : '&#x4b;',
			'icon-libreoffice' : '&#x4c;',
			'icon-pencil' : '&#x4d;',
			'icon-file' : '&#x4e;',
			'icon-new' : '&#x4f;',
			'icon-copy' : '&#x50;',
			'icon-folder' : '&#x51;',
			'icon-folder-2' : '&#x52;',
			'icon-screen' : '&#x53;',
			'icon-comments' : '&#x54;',
			'icon-comments-2' : '&#x55;',
			'icon-comments-3' : '&#x56;',
			'icon-comments-4' : '&#x57;',
			'icon-search' : '&#x58;',
			'icon-zoom-in' : '&#x59;',
			'icon-zoom-out' : '&#x5a;',
			'icon-cog' : '&#x5b;',
			'icon-pie' : '&#x5c;',
			'icon-bars' : '&#x5d;',
			'icon-stats-up' : '&#x5e;',
			'icon-cancel' : '&#x5f;',
			'icon-cancel-2' : '&#x60;',
			'icon-minus-2' : '&#x61;',
			'icon-plus-2' : '&#x62;',
			'icon-help' : '&#x63;',
			'icon-attachment' : '&#x64;',
			'icon-bookmark' : '&#x65;',
			'icon-bookmark-2' : '&#x66;',
			'icon-star' : '&#x67;',
			'icon-star-2' : '&#x69;',
			'icon-star-3' : '&#x68;',
			'icon-heart' : '&#x6a;',
			'icon-heart-2' : '&#x6b;',
			'icon-thumbs-up' : '&#x6c;',
			'icon-thumbs-down' : '&#x6d;',
			'icon-link' : '&#x6e;',
			'icon-link-2' : '&#x6f;',
			'icon-clipboard' : '&#x70;',
			'icon-clipboard-2' : '&#x71;',
			'icon-windows' : '&#x72;',
			'icon-wrench' : '&#x24;',
			'icon-html5' : '&#x73;',
			'icon-html5-2' : '&#x74;',
			'icon-css3' : '&#x75;',
			'icon-camera' : '&#x76;',
			'icon-picture' : '&#x77;',
			'icon-pictures' : '&#x78;',
			'icon-mic' : '&#x79;',
			'icon-user' : '&#x7a;',
			'icon-user-2' : '&#x7b;',
			'icon-user-3' : '&#x7c;',
			'icon-cube' : '&#x7d;',
			'icon-puzzle' : '&#xe000;',
			'icon-upload' : '&#xe001;',
			'icon-smiley' : '&#xe002;',
			'icon-location' : '&#xe003;',
			'icon-clock' : '&#xe004;',
			'icon-printer' : '&#xe005;',
			'icon-google' : '&#xe006;',
			'icon-eye' : '&#xe007;',
			'icon-embed' : '&#xe008;',
			'icon-code' : '&#xe009;',
			'icon-delicious' : '&#xe00a;',
			'icon-pinterest' : '&#xe00b;',
			'icon-pinterest-2' : '&#xe00c;',
			'icon-file-word' : '&#xe00d;',
			'icon-file-excel' : '&#xe00e;',
			'icon-file-css' : '&#xe00f;',
			'icon-file-xml' : '&#xe010;'
		},
		els = document.getElementsByTagName('*'),
		i, attr, html, c, el;
	for (i = 0; i < els.length; i += 1) {
		el = els[i];
		attr = el.getAttribute('data-icon');
		if (attr) {
			addIcon(el, attr);
		}
		c = el.className;
		c = c.match(/icon-[^\s'"]+/);
		if (c) {
			addIcon(el, icons[c[0]]);
		}
	}
};